AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 300
Resources:
  Article:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: article
    Type: AWS::DynamoDB::Table
  AudioTranscoder:
    Properties:
      CodeUri: s3://mohamed-chaaben-bucket-central-1/04f5bd6911271963590c0fbf10cffdeb
      Environment:
        Variables:
          BUCKET_NAME: serverless-xke-demo
      Events:
        DynamoDB1:
          Properties:
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - Article
              - StreamArn
          Type: DynamoDB
      Handler: transcoder.handler
      Policies:
      - AmazonPollyFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  RssReader:
    Properties:
      CodeUri: s3://mohamed-chaaben-bucket-central-1/7e63761bc71b924078b843381c7417e4
      Environment:
        Variables:
          ARTICLE_TABLE: article
      Events:
        EventCloudWatch:
          Properties:
            Schedule: rate(2400 minutes)
          Type: Schedule
      Handler: reader.handler
      Policies:
      - AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ServerlessXkeDemoBucket:
    Properties:
      BucketName: serverless-xke-demo
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
