AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  AudioTranscoder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: audio-transcoder/
      Handler: transcoder.handler
      Runtime: nodejs8.10
      Policies:
        - AmazonPollyFullAccess
        - AmazonS3FullAccess
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Article
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Environment:
        Variables:
          BUCKET_NAME: serverless-xke-demo

  RssReader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: rss-reader/
      Handler: reader.handler
      Runtime: nodejs8.10
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        EventCloudWatch:
          Type: Schedule
          Properties:
            Schedule: rate(2400 minutes)
      Environment:
        Variables:
          ARTICLE_TABLE: article

  ServerlessXkeDemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-xke-demo
  Article:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: article
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
#Outputs:
#
#  AudioTranscoderIamRole:
#    Description: "Implicit IAM Role created for audio transcoder function"
#    Value: !GetAtt AudiTranscoderFunction.Arn
#  RssReaderFunctionIamRole:
#    Description: "Implicit IAM Role created for audio transcoder function"
#    Value: !GetAtt AudiTranscoderFunction.Arn


#sam local invoke RssReaderFunction -e event.json
#AWS_PROFILE=mchaaben sam package     --template-file template.yaml     --output-template-file packaged.yaml     --s3-bucket mohamed-chaaben-bucket-central-1
#AWS_PROFILE=mchaaben sam deploy     --template-file packaged.yaml  --capabilities CAPABILITY_IAM   --stack-name sam-app
#AWS_PROFILE=mchaaben aws cloudformation delete-stack --stack-name sam-app
